### ISSUE TITLE
The Doctrine constraint requires using an unmaintained version

### ISSUE THREAD

**Issue by stof** [yucca-php/yucca#14]
Currently, Yucca depends on ``doctrine/dbal: 2.3.*``. this is a bad constraint given that the 2.3 branch of DBAL is not maintained anymore (the stable branch is 2.4 since a long time, and 2.5 is in RC phase).

Given that Doctrine follows semver, using the semantic constraint would be much better

**Comment by rjanot** [comment]
Closed by commit : https://github.com/yucca-php/yucca/commit/43168f0dd3d2d7442e4df8f8df7f38da10725a1c
