### ISSUE TITLE
Support newer version of Doctrine

### ISSUE THREAD

**Issue by ooga** [yucca-php/yucca#17]
Your last release depends on `doctrine/dbal: 2.3.*`

Could you make a new release with at least this fix https://github.com/yucca-php/yucca/commit/43168f0dd3d2d7442e4df8f8df7f38da10725a1c

I tried to fork and submit a PR but your master is to different from the release `release-1.5.2`
https://github.com/ooga/yucca/commits/v1-master

**Comment by rjanot** [comment]
Hello,

sure, I will check ASAP (between christmas and new year), is it ok for you to wait until then ?

**Comment by ooga** [comment]
Hello and thank you for your quick reply,

I can wait, 
thank you.

**Comment by rjanot** [comment]
Sorry for being late, I just added the tag release-1.6.0
